[package]
authors = ["Paul Houghton <paulirotta@gmail.com>"]
edition = "2024"
name = "openscad-make"
resolver = "3"
version = "0.8.1"

[dependencies]
clap = "4.5.51"
glob = "0.3.3"
rayon = "1.11.0"

[profile.release]
lto = true
