[package]
authors = ["Paul Houghton <paulirotta@gmail.com>"]
edition = "2024"
name = "openscad-make"
resolver = "2"
version = "0.7.0"

[dependencies]
clap = "4.5"
glob = "0.3"
rayon = "1.10"

[profile.release]
lto = true
