[package]
name = "openscad-make"
version = "0.6.0"
authors = ["Paul Houghton <paulirotta@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3"
rayon = "1.3"
clap = "4.0"

[profile.release]
lto = true
