[package]
name = "openscad-make"
version = "0.6.3"
authors = ["Paul Houghton <paulirotta@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
glob = "0.3"
rayon = "1.10"
clap = "4.5"

[profile.release]
lto = true
